const express = require("express");
const weights = require("../routes/weights");
const mobileWeights = require("../routes/mobileWeights");
const users = require("../routes/users");
const collectionPoints = require("../routes/collectionPoints");
const addresses = require("../routes/addresses");
const coupons = require("../routes/coupons");
const couponClaims = require("../routes/couponClaims");
const auth = require("../routes/auth");
const locations = require("../routes/locations");
const roles = require("../routes/roles");
const organizations = require("../routes/organizations");
const entities = require("../routes/entities");
const colors = require("../routes/colors");
const devices = require("../routes/devices");
const permissionsoptions = require("../routes/permissionsoptions");
const partnerTypes = require("../routes/partnerTypes");
const uploads = require("../routes/uploads");
const deviceTypes = require("../routes/deviceTypes");
const offerTypes = require("../routes/offerTypes");
const oldBagCodes = require("../routes/oldBagCodes");
const newsletter = require("../routes/newsletter");
const discounts = require("../routes/discounts");
const mobileCoupons = require("../routes/mobileCoupons");
const mobileCouponClaims = require("../routes/mobileCouponClaims");
//const error = require('../middleware/error');

module.exports = function (app, config) {
  const apiPath = config.get("apiPath");
  app.use(express.json());
  app.use(apiPath + "/mobile/weights", mobileWeights);
  app.use(apiPath + "/weights", weights); 
  app.use(apiPath + "/users", users);          
  app.use(apiPath + "/auth", auth);
  app.use(apiPath + "/collection_points", collectionPoints);
  app.use(apiPath + "/addresses", addresses);
  app.use(apiPath + "/coupons", coupons);
  app.use(apiPath + "/couponClaims", couponClaims);
  app.use(apiPath + "/locations", locations);
  app.use(apiPath + "/roles", roles);
  app.use(apiPath + "/organizations", organizations);
  app.use(apiPath + "/entities", entities);
  app.use(apiPath + "/colors", colors);
  app.use(apiPath + "/devices", devices);
  app.use(apiPath + "/partner_types", partnerTypes);
  app.use(apiPath + "/permissionsoptions", permissionsoptions);
  app.use(apiPath + "/uploads", uploads);
  app.use(apiPath + "/deviceTypes", deviceTypes);
  app.use(apiPath + "/offerTypes", offerTypes);
  app.use(apiPath + "/codes", oldBagCodes);
  app.use(apiPath + "/newsletter", newsletter);
  app.use(apiPath + "/discounts", discounts);
  app.use(apiPath + "/mobile/coupons", mobileCoupons);
  app.use(apiPath + "/mobile/couponClaims", mobileCouponClaims);
  //    app.use(error);
};
