const SU = 0;
const CREATE = 1;
const RETRIEVE = 2;
const RETRIEVE_ORGANIZATION = 3;
const RETRIEVE_OWN = 4;
const UPDATE = 5;
const UPDATE_ORGANIZATION = 6;
const UPDATE_OWN = 7;
const DELETE = 8;
const DELETE_ORGANIZATION = 9;
const DELETE_OWN = 10;
const CHANGE_CREATOR = 11;
const CHANGE_UPDATER = 12;
const CHANGE_ORGANIZATION = 13;
const CHANGE_ORGANIZATION_CREATOR = 14;
const CHANGE_ORGANIZATION_UPDATER = 15;

module.exports.SU = SU;
module.exports.CREATE = CREATE;
module.exports.RETRIEVE = RETRIEVE;
module.exports.RETRIEVE_ORGANIZATION = RETRIEVE_ORGANIZATION;
module.exports.RETRIEVE_OWN = RETRIEVE_OWN;
module.exports.UPDATE = UPDATE;
module.exports.UPDATE_ORGANIZATION = UPDATE_ORGANIZATION;
module.exports.UPDATE_OWN = UPDATE_OWN;
module.exports.DELETE = DELETE;
module.exports.DELETE_ORGANIZATION = DELETE_ORGANIZATION;
module.exports.DELETE_OWN = DELETE_OWN;
module.exports.CHANGE_CREATOR = CHANGE_CREATOR;
module.exports.CHANGE_UPDATER = CHANGE_UPDATER;
module.exports.CHANGE_ORGANIZATION = CHANGE_ORGANIZATION;
module.exports.CHANGE_ORGANIZATION_CREATOR = CHANGE_ORGANIZATION_CREATOR;
module.exports.CHANGE_ORGANIZATION_UPDATER = CHANGE_ORGANIZATION_UPDATER;

module.exports.actionGroups = {
  read: [RETRIEVE, RETRIEVE_ORGANIZATION, RETRIEVE_OWN],
  update: [UPDATE, UPDATE_ORGANIZATION, UPDATE_OWN],
  delete: [DELETE, DELETE_ORGANIZATION, DELETE_OWN],
};
